# Generated by Django 4.2.1 on 2023-05-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
